# Generated by Django 5.0.7 on 2026-07-08 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_contract_productprice_auditlog_action_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=32),
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='persistence.payment')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='persistence.receipt')),
            ],
            options={
                'indexes': [models.Index(fields=['payment', 'receipt'], name='persistence_payment_2b8915_idx')],
                'unique_together': {('payment', 'receipt')},
            },
        ),
        migrations.CreateModel(
            name='SupplierSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_suppliers', to='persistence.warehouse')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sites', to='persistence.supplier')),
            ],
            options={
                'indexes': [models.Index(fields=['supplier', 'site'], name='persistence_supplie_eace4d_idx')],
                'unique_together': {('supplier', 'site')},
            },
        ),
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_users', to='persistence.warehouse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'site'], name='persistence_user_id_76631c_idx')],
                'unique_together': {('user', 'site')},
            },
        ),
    ]
