# Generated by Django 5.0.7 on 2026-07-13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_alter_warehouse_status_paymentallocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE_RECEIPT', 'Purchase Receipt'), ('SITE_ISSUE', 'Site Issue'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='persistence.product')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='persistence.warehouse')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [
                    models.Index(fields=['site', 'product', 'date'], name='persistence_site_p_37cf97_idx'),
                    models.Index(fields=['transaction_type', 'date'], name='persistence_transac_f4a1f7_idx'),
                    models.Index(fields=['reference_number'], name='persistence_referen_69f1dc_idx'),
                ],
            },
        ),
        migrations.RunSQL(
            sql=(
                "CREATE VIEW vw_SiteStock AS "
                "SELECT ROW_NUMBER() OVER (ORDER BY site_id, product_id) AS id, "
                "site_id AS SiteID, product_id AS ProductID, SUM(quantity) AS QuantityOnHand "
                "FROM persistence_inventorytransaction "
                "GROUP BY site_id, product_id"
            ),
            reverse_sql="DROP VIEW IF EXISTS vw_SiteStock",
        ),
    ]
